import { TOrder } from "@/types/Orders";

export const exampleOrders: TOrder[] = [
	{
		id: 1,
		name: "Коврик",
		image: "/items/carpet.png",
		orderId: 456789123258,
		shopName: "Shop name",
		productName: "Product",
		address: "Алматинская, Карасайский, Ельтай, к.х. АКХ Жетысу, уч. 1095",
		price: 20000,
		status: "Получено",
		eCheck: "Детали чека",
		card: {
			id: 1,
			cardId: 123,
			isActive: true,
			type: "Visa",
		},
	},
	{
		id: 2,
		name: "Руль",
		image: "/items/steeringWheel.png",
		orderId: 456789123258,
		shopName: "Shop name",
		productName: "Product",
		address: "Алматинская, Карасайский, Ельтай, к.х. АКХ Жетысу, уч. 1095",
		price: 5000,
		status: "Заказ оплачен и ожидает обработки",
		eCheck: "Детали чека",
		card: {
			id: 1,
			cardId: 456789123258,
			isActive: true,
			type: "Visa",
		},
	},
	{
		id: 3,
		name: "Колеса",
		image: "/items/wheelItems.png",
		orderId: 456789123258,
		shopName: "Shop name",
		productName: "Product",
		address: "Алматинская, Карасайский, Ельтай, к.х. АКХ Жетысу, уч. 1095",
		price: 10000,
		status: "Ожидает в пункте выдачи",
		eCheck: "Детали чека",
		card: {
			id: 1,
			cardId: 456789123258,
			isActive: true,
			type: "Visa",
		},
	},
];
