import { TFilteredItemInfo } from "@/types/items/Item";

export const exampleBrands = [
	{ value: "BMW", label: "BMW" },
	{ value: "AUDI", label: "AUDI" },
	{ value: "TOYOTA", label: "TOYOTA" },
	{ value: "HONDA", label: "HONDA" },
	{ value: "KIA", label: "KIA" },
	{ value: "Lexus", label: "Lexus" },
];

export const exampleFilterTypes = [
	{ value: "seatCase", label: "Чехол на сиденье" },
	{ value: "seatCase", label: "Коврики в салон автомобиля" },
	{ value: "seatCase", label: "Оплетка на руль" },
	{ value: "seatCase", label: "Наклейка для автомобиля" },
	{ value: "seatCase", label: "Комплект багажника" },
	{ value: "seatCase", label: "Руль" },
];

export const exampleColors = [
	{ value: "black", label: "Чёрный" },
	{ value: "white", label: "Белый" },
	{ value: "red", label: "Красный" },
	{ value: "blue", label: "Синий" },
];

export const exampleManufacturers = [
	{ value: "kazakhstan", label: "Казахстан" },
	{ value: "russia", label: "Россия" },
	{ value: "china(taiwan)", label: "Китай(Тайвань)" },
	{ value: "china(hongkong)", label: "Китай(Гонконг)" },
	{ value: "germany", label: "Германия" },
	{ value: "belorus", label: "Белорусь" },
];

export const MIN_PRICE = 0;
export const MAX_PRICE = 100000;

export const exampleSearchKeyWords = [
	{
		value: "autoItems",
		name: "Аксессуары для авто",
	},
	{
		value: "autoItemsOptom",
		name: "Аксессуары для авто оптом",
	},
	{
		value: "cargoItems",
		name: "Аксессуары для грузовых авто",
	},
];

export const exampleData: TFilteredItemInfo[] = [
	{
		id: 1,
		name: "Руль",
		price: 50000,
		apPrice: 24500,
		currentPrice: 25000,
		discount: 50,
		rating: 3.9,
		comments: 220,
		favorite: true,
		images: ["/items/case.png", "/items/carpet.png"],
		marketName: "Магазин авточехлов и аксессуаров «АВТОПИЛОТ",
		autoType: {
			id: 1,
			brand: "BMW",
			model: "M5",
			generation: "F10 (2013-2015)",
			manuFacturer: "china(hongkong)",
		},
		color: "black",
		itemType: "seatCase",
		brand: "Autoprofi",
		material: "кожа",
		description: "Some text",
	},
	{
		id: 2,
		name: "Чехол на сиденье",
		price: 18000,
		apPrice: 17500,
		currentPrice: null,
		discount: null,
		rating: 4.2,
		comments: 150,
		favorite: false,
		images: ["/items/case.png", "/items/case.png"],
		marketName: "Магазин авточехлов и аксессуаров «АВТОПИЛОТ",
		autoType: {
			id: 2,
			brand: "AUDI",
			model: "A4",
			generation: "B8 (2008-2015)",
			manuFacturer: "germany",
		},
		color: "white",
		itemType: "seatCase",
		brand: "Autoprofi",
		material: "ткань",
		description: "High quality seat cover",
	},
	{
		id: 3,
		name: "Коврики",
		price: 12000,
		apPrice: 11500,
		currentPrice: null,
		discount: null,
		rating: 4.0,
		comments: 75,
		favorite: false,
		images: ["/items/carpet.png"],
		marketName: "Магазин авточехлов и аксессуаров «АВТОПИЛОТ",
		autoType: {
			id: 3,
			brand: "TOYOTA",
			model: "Camry",
			generation: "XV50 (2011-2017)",
			manuFacturer: "russia",
		},
		color: "gray",
		itemType: "carpet",
		brand: "Autoprofi",
		material: "резина",
		description: "Comfortable floor mats",
	},
	{
		id: 4,
		name: "Оплетка на руль",
		price: 9000,
		apPrice: 8500,
		currentPrice: null,
		discount: null,
		rating: 3.8,
		comments: 200,
		favorite: true,
		images: ["/items/case.png"],
		marketName: "Магазин авточехлов и аксессуаров «АВТОПИЛОТ",
		autoType: {
			id: 4,
			brand: "HONDA",
			model: "Civic",
			generation: "10th Gen (2015-2020)",
			manuFacturer: "china(taiwan)",
		},
		color: "red",
		itemType: "seatCase",
		brand: "Autoprofi",
		material: "искусственная кожа",
		description: "Premium steering wheel wrap",
	},
	{
		id: 5,
		name: "Наклейка для автомобиля",
		price: 5000,
		apPrice: 4500,
		currentPrice: null,
		discount: null,
		rating: 4.5,
		comments: 50,
		favorite: false,
		images: ["/items/seatCovers.png", "/items/case.png"],
		marketName: "Магазин авточехлов и аксессуаров «АВТОПИЛОТ",
		autoType: {
			id: 5,
			brand: "KIA",
			model: "Sportage",
			generation: "QL (2016-2021)",
			manuFacturer: "belorus",
		},
		color: "blue",
		itemType: "decal",
		brand: "Autoprofi",
		material: "пластик",
		description: "Stylish car decal",
	},
	{
		id: 6,
		name: "Комплект багажника",
		price: 30000,
		currentPrice: null,
		discount: null,
		rating: 4.7,
		comments: 180,
		favorite: true,
		images: ["/items/evaCarpet.png"],
		marketName: "Магазин авточехлов и аксессуаров «АВТОПИЛОТ",
		autoType: {
			id: 6,
			brand: "Lexus",
			model: "RX",
			generation: "AL20 (2015-2022)",
			manuFacturer: "kazakhstan",
		},
		color: "black",
		itemType: "trunkSet",
		brand: "Autoprofi",
		material: "композит",
		description: "Full trunk kit",
	},
	{
		id: 7,
		name: "Фара",
		price: 22000,
		currentPrice: null,
		discount: null,
		rating: 4.1,
		comments: 95,
		favorite: false,
		images: ["/items/steeringWheel.png", "/items/case.png"],
		marketName: "Магазин авточехлов и аксессуаров «АВТОПИЛОТ",
		autoType: {
			id: 7,
			brand: "BMW",
			model: "X5",
			generation: "E70 (2006-2013)",
			manuFacturer: "china(hongkong)",
		},
		color: "silver",
		itemType: "headlight",
		brand: "Autoprofi",
		material: "пластик",
		description: "LED headlight",
	},
	{
		id: 8,
		name: "Бампер",
		price: 27000,
		currentPrice: null,
		discount: null,
		rating: 3.9,
		comments: 130,
		favorite: true,
		images: ["/items/wheelItems.png"],
		marketName: "Магазин авточехлов и аксессуаров «АВТОПИЛОТ",
		autoType: {
			id: 8,
			brand: "AUDI",
			model: "Q5",
			generation: "8M (2017-2022)",
			manuFacturer: "germany",
		},
		color: "black",
		itemType: "bumper",
		brand: "Autoprofi",
		material: "металл",
		description: "Reinforced bumper",
	},
	{
		id: 9,
		name: "Колесо",
		price: 15000,
		currentPrice: null,
		discount: null,
		rating: 4.3,
		comments: 80,
		favorite: false,
		images: ["/items/wheelItems.png"],
		marketName: "Магазин авточехлов и аксессуаров «АВТОПИЛОТ",
		autoType: {
			id: 9,
			brand: "TOYOTA",
			model: "RAV4",
			generation: "XA50 (2018-2022)",
			manuFacturer: "russia",
		},
		color: "silver",
		itemType: "wheel",
		brand: "Autoprofi",
		material: "алюминий",
		description: "Alloy wheel",
	},
	{
		id: 10,
		name: "Зеркало",
		price: 8000,
		currentPrice: null,
		discount: null,
		rating: 4.0,
		comments: 60,
		favorite: false,
		images: ["/items/case.png"],
		marketName: "Магазин авточехлов и аксессуаров «АВТОПИЛОТ",
		autoType: {
			id: 10,
			brand: "HONDA",
			model: "Accord",
			generation: "10th Gen (2018-2023)",
			manuFacturer: "china(taiwan)",
		},
		color: "white",
		itemType: "mirror",
		brand: "Autoprofi",
		material: "пластик",
		description: "Side mirror",
	},
];
