import {Item} from "@/types/Item";

export const items: Item[] = [
    {
        id: 1,
        name: "Качественный перешив руля, ручки кпп",
        price: 2000,
        currentPrice: 1500,
        discount: 25,
        rating: 3.6,
        comments: 382,
        images: [
            "/items/steeringWheel.png",
            "/items/case.png",
            "/items/evaCarpet.png",
            "/items/seatCovers.png",
            "/items/wheelItems.png",
            "/items/carpet.png",
        ],
    },
    {
        id: 2,
        name: "Коврики эва ева с бортами, eva с бортиками 3Д",
        price: 3200,
        currentPrice: null,
        discount: null,
        rating: 4.5,
        comments: 128,
        images: ["/items/evaCarpet.png"],
    },
    {
        id: 3,
        name: "ITEM 3",
        price: 4500,
        currentPrice: 3900,
        discount: 13,
        rating: 4.8,
        comments: 256,
        images: [
            "/items/seatCovers.png",
            "/items/wheelItems.png",
        ],
    },
    {
        id: 4,
        name: "ITEM 4",
        price: 1800,
        currentPrice: 1400,
        discount: 22,
        rating: 3.9,
        comments: 97,
        images: ["/items/carpet.png"],
    },
    {
        id: 5,
        name: "ITEM 5",
        price: 5000,
        currentPrice: null,
        discount: null,
        rating: 4.2,
        comments: 412,
        images: [
            "/items/steeringWheel.png",
            "/items/case.png",
        ],
    },
    {
        id: 6,
        name: "ITEM 6",
        price: 2300,
        currentPrice: 1900,
        discount: 17,
        rating: 3.5,
        comments: 189,
        images: ["/items/evaCarpet.png"],
    },
    {
        id: 7,
        name: "ITEM 7",
        price: 2900,
        currentPrice: null,
        discount: null,
        rating: 4.0,
        comments: 275,
        images: [
            "/items/seatCovers.png",
            "/items/wheelItems.png",
        ],
    },
    {
        id: 8,
        name: "ITEM 8",
        price: 3700,
        currentPrice: 3300,
        discount: 11,
        rating: 4.6,
        comments: 132,
        images: ["/items/carpet.png"],
    },
    {
        id: 9,
        name: "ITEM 9",
        price: 2600,
        currentPrice: 2200,
        discount: 15,
        rating: 4.1,
        comments: 321,
        images: [
            "/items/steeringWheel.png",
            "/items/case.png",
        ],
    },
    {
        id: 10,
        name: "ITEM 10",
        price: 3400,
        currentPrice: null,
        discount: null,
        rating: 3.7,
        comments: 88,
        images: ["/items/evaCarpet.png"],
    },
];
